### PR TITLE
i hate typos

### PR DESCRIPTION
**Pull request by eris-webserv**
it might be 1 letter but IDC
just- this is my first pull and I actually want to be useful

### CODE REVIEW

**Comment by LixieWulf** [comment]
Sand water all over again.
Lmao.

**Comment by eris-webserv** [comment]
now it's 2 letters.

**Comment by eris-webserv** [comment]
https://github.com/sk7725/BetaMindy/pull/46
***the typo sniping begins***

**Comment by MEEPofFaith** [comment]
aaaa

**Pull request merged**
